
import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "@/reactQuery/QueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" >
      <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
        precedence="default"
      />
      <body
      >
        <QueryProvider>
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
